In [11]:
# Import ML framework and tabular, discretised, and plotting libraries.
import torch, pandas as pd, numpy as np, matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu117


In [12]:
# 1D value : Lower(a)
scalar = 1
scalar_tensor = torch.tensor(scalar)
print(scalar_tensor.ndim,scalar_tensor.item())

# Recall that vectors have magnitude and direction : Lower(y)
vector = [1,2]
vector_tensor = torch.tensor(vector)
print(vector_tensor.ndim,vector_tensor.shape)

# 2D values : Upper(Q)
matrix = [[2,5],[4,3]]
matrix_tensor = torch.tensor(matrix)
print(matrix_tensor.ndim,matrix_tensor.shape)

#n-dimensional matrix structure : Upper(X)
tensor = torch.rand(1,4,6)
print(tensor.ndim,tensor.shape)

0 1
1 torch.Size([2])
2 torch.Size([2, 2])
3 torch.Size([1, 4, 6])


In [13]:
# Create image tensor characteristic
random_img = torch.rand(size=(3,224,224)) # h, w, channels (RGB)

# Zero/Ones tensor
zero_tensor = torch.zeros(size=(3,224,224))
ones_tensor = torch.ones(size=(3,224,224))

# data types
ones_tensor.dtype

torch.float32

In [23]:
# Torch ranges and tensor operations
x = torch.arange(start=1,end=11,step=1)
ten_zeros = torch.zeros_like(x)

f32 = torch.tensor([1,2,3],dtype=torch.float32,device="cuda",requires_grad=False)
print(f32.dtype,f32.device,f32.requires_grad)

## Tensor datatypes, shape and device are most common errors.
f16 = f32.type(torch.float16)

# Tensor operations
## Tensors operate just like np arrays.

random_img.shape

torch.matmul(random_img,random_img)
a = torch.argmin(random_img)
b = torch.argmax(random_img)
print(f"Location of min value: {a}, Location of max value: {b}".format(a=a, b=b))
print(torch.mean(f16))

torch.float32 cuda:0 False
Location of min value: 128642, Location of max value: 131468
tensor(2., device='cuda:0', dtype=torch.float16)


In [35]:
# Reshaping tensors

# m * n must = number of elements
x.reshape(5,2)

# tensor.view() is an alternative to reshape

torch.stack([x,x,x],dim=0)

x.squeeze() # remove all single dimensions
x.unsqueeze(dim=0) # add a dimension

# torch.permute() rearranges the dimensions order

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 1 is not equal to len(dims) = 2

In [49]:
# Tensor Indexing
x = torch.arange(1,10).reshape(1,3,3)
# x[first dimension, second dimension, third dimension]
#x[0,0,0] is the same as x[0][0][0]

print(x[0],"\n",x[:,0],"\n",x[:,:,2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
 tensor([[1, 2, 3]]) 
 tensor([[3, 6, 9]])


In [59]:
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.rand(size=(3,3),device=device)
# if not on GPU, tensor_on_gpu = tensor.to(device)
# to compute numpy, tensor_on_gpu.cpu().numpy() cuz numpy can't compute on GPU

tensor([[1.1734, 1.1895, 1.3603],
        [1.1895, 1.7859, 1.6664],
        [1.3603, 1.6664, 2.1616]], device='cuda:0')


In [66]:
# Creating and multiplying random tensors in a contained seed
SEED = 42
torch.manual_seed(SEED)
random_tensor = torch.rand(size=(7,7))
multiplication = torch.matmul(random_tensor,torch.rand(size=(1,7)).T)
print(multiplication)

# GPU Seed
torch.cuda.manual_seed(1234)
tensor_one, tensor_two = torch.rand(size=(2,3),device="cuda"), torch.rand(size=(2,3),device="cuda")
final = torch.matmul(tensor_one,tensor_two.T)
print(final.max(),final.min(),"\n",final.argmax(),final.argmin())

torch.manual_seed(7)
tensor_large = torch.rand(size=(1,1,1,10))
tensor_shrunk = torch.squeeze(tensor_large)
print(tensor_large.shape,tensor_shrunk.shape)

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])
tensor(0.7668, device='cuda:0') tensor(0.2786, device='cuda:0') 
 tensor(1, device='cuda:0') tensor(0, device='cuda:0')
torch.Size([1, 1, 1, 10]) torch.Size([10])
